### ISSUE TITLE
Assertion in Eigen when num_modes > dim

### ISSUE THREAD

**Issue by Meekohi** [CVLearner/Mixture-of-Gaussians#1]
```
Assertion failed: (index >= 0 && index < size()), function operator(), file /usr/local/Cellar/eigen/3.2.4/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h, line 394.
Abort trap: 6
```

I get this error when I try to run `em_gmm()` on data with `num_modes > dim`.

**Comment by pppoe** [comment]
Thanks @Meekohi , I will look into this when I got a chance. Help on this is highly welcomed!

**Comment by Meekohi** [comment]
Note: this only happens if `should_fit_spherical_gaussian=false`.

**Comment by Meekohi** [comment]
Ah of course. Problem is at https://github.com/CVLearner/Mixture-of-Gaussians/blob/master/em_gmm.cc#L98-L101

is `dim` supposed to be `num_modes` instead?

**Comment by pppoe** [comment]
Thanks!
